export const IPC_CHANNELS = {
  DIALOG_SELECT_FOLDERS: "dialog:select-folders",
  LIBRARY_GET_ALL: "library:get-all",
  LIBRARY_SCAN: "library:scan",
  LIBRARY_CANCEL_SCAN: "library:cancel-scan",
  LIBRARY_REMOVE_FOLDER: "library:remove-folder",
  LIBRARY_SCAN_PROGRESS: "library:scan-progress",
  PLAYLIST_SAVE: "playlist:save",
  PLAYLIST_DELETE: "playlist:delete",
  FAVORITE_TOGGLE: "favorite:toggle",
  HISTORY_RECORD_PLAY: "history:record-play",
  SETTINGS_GET: "settings:get",
  SETTINGS_SET: "settings:set",
  SYSTEM_SHOW_ITEM_IN_FOLDER: "system:show-item-in-folder",
  WINDOW_MINIMIZE: "window:minimize",
  WINDOW_MAXIMIZE: "window:maximize",
  WINDOW_CLOSE: "window:close",
  NOTIFICATION_SHOW: "notification:show",
  WINDOW_IS_MAXIMIZED: "window:is-maximized",
  MEDIA_COMMAND: "media:command",
} as const;
